### ISSUE TITLE
belgiumrca4.crt differs from http://repository.eid.belgium.be/certificates.php?cert=Root&lang=nl

### ISSUE THREAD

**Issue by dwagelaar** [e-Contract/jtrust#1]
The belgiumrca4.crt bundled with jtrust (version 2.0.10) differs from the Belgium Root CA 4 Self-signed certificate provided on http://repository.eid.belgium.be/certificates.php?cert=Root&lang=nl (OK, that's not even https...)

key ID matches (67 e8 f1 4e 4f b3 b5 f3 07 6f 08 9c 0c 83 d9 7a d9 5b e7 49)
fingerprint differs:
  jtrust: ‎cd 41 86 bc d9 38 ca 5c 19 61 0f 74 c7 62 b2 3a cf 07 a5 64
  repository: ‎6b 97 f8 99 56 59 2a 9b 20 10 19 75 27 b0 dc 4c a5 ac 9b e0
expiry date differs:
  jtrust: ‎vrijdag ‎28 ‎januari ‎2028 13:00:00
  repository: ‎vrijdag ‎22 ‎oktober ‎2032 13:00:00

This causes root certificate validation for recent eID cards (issued in March 2017) to fail.

**Comment by dwagelaar** [comment]
The jtrust version of the Belgium Root CA 4 Self-signed certificate is actually in the wild as well, e.g. on an eID issued on January 13th, 2017. The new version of the Belgium Root CA 4 Self-signed certificate should probably be added to the list of trusted roots.

**Comment by nquirynen** [comment]
When will the version with this fix (2.0.11) be released?
