### ISSUE TITLE
Update certificate policies in BelgianTrustValidatorFactory

### ISSUE THREAD

**Issue by alexvr** [e-Contract/jtrust#9]
Hi,

I believe the new certificate policies as described in the _Certificate Policy and Certificate Practice Statement_ published on the [new eID repository](https://repository.eidpki.belgium.be/#/terms) still need to be added to the `BelgianTrustValidatorFactory`.

In short these are the policies that should be included:
![image](https://user-images.githubusercontent.com/9627306/123056888-a602e800-d407-11eb-9c18-5b9167860957.png)

I can provide a PR if this is of help.

Kind regards, Alexander.

**Comment by petermylemans** [comment]
Same for national registry but with policy OID "2.16.56.13.6.0.1".
